apiVersion: skaffold/v2alpha3
kind: Config
build:
  local:
    push: false   
  artifacts:

  - image: gcr.io/edb-containers/edb-operator
    context: .
    docker:
      dockerfile: docker/containers/edb-operator/Dockerfile

  tagPolicy:
    gitCommit: {}

