apiVersion: skaffold/v2alpha3
kind: Config
build:
  local:
    push: true
  artifacts:

  - image: gcr.io/williams-heavy-industries/recert-operator
    context: .
    docker:
      dockerfile: docker/operator/Dockerfile

  - image: gcr.io/williams-heavy-industries/recert-nginx
    context: .
    docker:
      dockerfile: docker/nginx/Dockerfile

  tagPolicy:
    gitCommit: {}

