{{- if .Values.repo.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "edb.name" . }}-pullsecret
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{- end }}
