apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: sslproxies.williamsheavyindustries.com
spec:
  group: williamsheavyindustries.com
  names:
    kind: SSLProxy
    listKind: SSLProxyList
    plural: sslproxies
    singular: sslproxy
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: SSLProxy is the Schema for the sslproxies API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: SSLProxySpec defines the desired state of SSLProxy
            properties:
              loadBalancerIP:
                type: string
              replicas:
                format: int32
                type: integer
              reverseProxy:
                type: string
              selector:
                additionalProperties:
                  type: string
                type: object
            required:
            - selector
            type: object
          status:
            description: SSLProxyStatus defines the observed state of SSLProxy
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
