apiVersion: apps/v1
kind: Deployment
metadata:
  name: edb-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: edb-operator
  template:
    metadata:
      labels:
        name: edb-operator
    spec:
      serviceAccountName: edb-operator
      containers:
        - name: edb-operator
          # Replace this with the built image name
          image: {{ .Values.edbOperator }}
          command:
          - edb-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "edb-operator"
