apiVersion: apps/v1
kind: Deployment
metadata:
  name: recert-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: recert-operator
  template:
    metadata:
      labels:
        name: recert-operator
    spec:
      serviceAccountName: operator
      containers:
        - name: operator
          # Replace this with the built image name
          image: {{ .Values.recertOperator }} 
          command:
          - operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace

            - name: SERVICE_ACCOUNT
              value: operator

            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name

            - name: OPERATOR_NAME
              value: "operator"
