## Metadata for EDB Container Platform configuration
## This metadata is used to augment the values.yaml for configuration of the Helm chart installation

## Licensing metadata
licensing:
  __metadata:
    label: "End-User License Agreement"
  acceptEULA:
    __metadata:
      name: "acceptEULA"
      label: "Accept End-User License Agreement"
      description: "Indicates whether user accepts the end-user license agreement."
      type: "string"
      immutable: "false"
      required: true

## Image configuration metadata
image:
  __metadata:
    label: "Docker image configuration"
  repository:
    __metadata:
      name: "Repository"
      label: "Docker Repository"
      description: "Docker registry to pull image from."
      type: "string"
      immutable: "false"
      required: true
  pullPolicy:
    __metadata:
      name: "pullPolicy"
      label: "Docker image pull policy"
      description: "Always, Never, or IfNotPresent. Defaults to IfNotPresent"
      type: "string"
      immutable: "false"
      required: true
      options:
      - label: "IfNotPresent"
        value: "IfNotPresent"
      - label: "Always"
        value: "Always"
      - label: "Never"
        value: "Never"
  pullSecret:
    __metadata:
      name: "pullSecret"
      label: "Docker Repository secret"
      description: "Secret to enable image pull from Docker registry."
      type: "string"
      immutable: "false"
      required: true

## Advanced Server specific configuration
database:
  __metadata:
    label: "Advanced Server configuration"
  image:
    __metadata:
      name: "image"
      label: "image name"
      description: "Name of container image."
      type: "string"
      immutable: "false"
      required: true
  imageTag:
    __metadata:
      name: "imageTag"
      label: "Image version"
      description: "Version of container image."
      type: "string"
      immutable: "false"
      required: true
  replicas:
    __metadata:
      name: "replicas"
      label: "Number of replicas"
      description: "Number of replicas (minimum 3)."
      type: "string"
      immutable: "false"
      required: true
  name:
    __metadata:
      name: "name"
      label: "Database name"
      description: "Name of Postgres database (defaults to edb)."
      type: "string"
      immutable: "false"
      required: true
  pgport:
    __metadata:
      name: "pgport"
      label: "Database port"
      description: "Database Port (defaults to 5444)."
      type: "string"
      immutable: "false"
      required: true
  user:
    __metadata:
      name: "user"
      label: "Database user"
      description: "Default database user (defaults to enterprisedb)."
      type: "string"
      immutable: "false"
      required: true
  enterprisedbPassword:
    __metadata:
      name: "enterprisedbPassword"
      label: "enterprisedb user password"
      description: "Password for enteprisedb user."
      type: "password"
      immutable: "false"
      required: false
  password:
    __metadata:
      name: "password"
      label: "Database user password"
      description: "Password for non-default database user."
      type: "password"
      immutable: "false"
      required: false
  replUser:
    __metadata:
      name: "replUser"
      label: "Replication user"
      description: "Database replication user."
      type: "string"
      immutable: "false"
      required: false
  replPassword:
    __metadata:
      name: "replUser"
      label: "Replication user password"
      description: "Password for database replication user."
      type: "password"
      immutable: "false"
      required: false
  localeParameter:
    __metadata:
      name: "localeParameter"
      label: "Locale"
      description: "Locale of database."
      type: "string"
      immutable: "false"
      required: false
  efmEmail:
    __metadata:
      name: "efmEmail"
      label: "Email"
      description: "Email for EFM."
      type: "string"
      immutable: "false"
      required: false
  nameserver:
    __metadata:
      name: "nameserver"
      label: "Name server for email"
      description: "Name Server for Email."
      type: "string"
      immutable: "false"
      required: false
  enableHAMode:
    __metadata:
      name: "enableHAMode"
      label: "Enable high availability mode"
      description: "Enable high availability mode (defaults to Yes)."
      type: "string"
      immutable: "false"
      required: false
  restoreFile:
    __metadata:
      name: "restoreFile"
      label: "Restore File"
      description: "Restore file location."
      type: "string"
      immutable: "false"
      required: false
  restoreDir:
    __metadata:
      name: "restoreDir"
      label: "Restore Directory"
      description: "Restore directory used for PITR."
      type: "string"
      immutable: "false"
      required: false
  initConfigmapVolume:
    __metadata:
      name: "initConfigmapVolume"
      label: "Initialization Configmap Volume"
      description: "Configmap volume used for custom initializations."
      type: "string"
      immutable: "false"
      required: false
  initdbOpts:
    __metadata:
      name: "initdbOpts"
      label: "initdb Options"
      description: "Custom initdb options."
      type: "string"
      immutable: "false"
      required: false
  reuseDataVolume:
    __metadata:
      name: "reuseDataVolume"
      label: "Reuse Data Volume"
      description: "Reuse existing data in data volume."
      type: "string"
      immutable: "false"
      required: false


## pgPool specific configuration
queryrouter:
  __metadata:
    label: "pgPool configuration"
  image:
    __metadata:
      name: "image"
      label: "image name"
      description: "Name of container image."
      type: "string"
      immutable: "false"
      required: true
  imageTag:
    __metadata:
      name: "imageTag"
      label: "Image version"
      description: "Version of container image."
      type: "string"
      immutable: "false"
      required: true
  replicas:
    __metadata:
      name: "replicas"
      label: "Number of replicas"
      description: "Number of replicas (minimum 2)."
      type: "string"
      immutable: "false"
      required: true
  enableHAMode:
    __metadata:
      name: "enableHAMode"
      label: "Enable high availability mode"
      description: "Enable high availability mode - witness node (defaults to No)."
      type: "string"
      immutable: "false"
      required: false

## BART configuration
backup:
  __metadata:
    label: "BART configuration"
  image:
    __metadata:
      name: "image"
      label: "image name"
      description: "Name of container image."
      type: "string"
      immutable: "false"
      required: true
  imageTag:
    __metadata:
      name: "imageTag"
      label: "Image version"
      description: "Version of container image."
      type: "string"
      immutable: "false"
      required: true
  enabled:
    __metadata:
      name: "enabled"
      label: "Enable backup"
      description: "Enable backup recovery functions."
      type: "string"
      immutable: "false"
      required: true
  hostAddress:
    __metadata:
      name: "hostAddress"
      label: "Host address"
      description: "Host address of BART server (defaults to localhost)."
      type: "string"
      immutable: "false"
      required: true
  numBackupsToKeep:
    __metadata:
      name: "numBackupsToKeep"
      label: "Number of backup to keep"
      description: "Number of backups to keep (retention policy)."
      type: "string"
      immutable: "false"
      required: false
  compressBackup:
    __metadata:
      name: "compressBackup"
      label: "Compress backups"
      description: "Backups stored in compressed format (tar.gz) (defaults to uncompressed)."
      type: "string"
      immutable: "false"
      required: false
  automateBackup:
    __metadata:
      name: "automateBackup"
      label: "Automate backups"
      description: "Backups performed on automated schedule."
      type: "string"
      immutable: "false"
      required: false
  backupSchedule:
    __metadata:
      name: "backupSchedule"
      label: "Backup schedule"
      description: "Schedule to follow for automated backups."
      type: "string"
      immutable: "false"
      required: false
  persistentVolume:
    __metadata:
      name: "persistentVolume"
      label: "Persistent volume"
      description: "Persistent volume to use for backups"
      type: "string"
      immutable: "false"
      required: true
  persistentVolumeClaim:
    __metadata:
      name: "persistentVolumeClaim"
      label: "Persistent volume claim"
      description: "Persistent volume claim to use for backups"
      type: "string"
      immutable: "false"
      required: true

## Archive configuration
archive:
  __metadata:
    label: "BART configuration"
  persistentVolume:
    __metadata:
      name: "persistentVolume"
      label: "Persistent volume"
      description: "Persistent volume to use for archives"
      type: "string"
      immutable: "false"
      required: true
  persistentVolumeClaim:
    __metadata:
      name: "persistentVolumeClaim"
      label: "Persistent volume claim"
      description: "Persistent volume claim to use for archives"
      type: "string"
      immutable: "false"
      required: true


## persistence configuration for EPAS (dynamic persistent volumes)
persistence:
  __metadata:
    label: "dynamic persistence configuration"
  enabled:
    __metadata:
      name: "enabled"
      label: "Enable persistence"
      description: "Enable persistence for EPAS containers."
      type: "string"
      immutable: "false"
      required: true
  storageClass:
    __metadata:
      name: "storageClass"
      label: "Existing storage class"
      description: "Existing Storage class to be used for persistence."
      type: "string"
      immutable: "false"
      required: false
  accessModes:
    __metadata:
      name: "accessMode"
      label: "Access mode of persistent volume claim"
      description: "Access mode of the persistent volume claim"
      type: "string"
      immutable: "false"
      required: true
  pvcSize:
    __metadata:
      name: "size"
      label: "Size of the persistent volume claim"
      description: "Size of the persistent volume claim"
      type: "string"
      immutable: "false"
      required: true

## Resource requests and limits configuration
resources:
  __metadata:
    label: "Resource configuration"
  requests:
    cpu:
      __metadata:
        label: "CPU request"
        description: "The requested CPU"
        type: "string"
        required: true
    memory:
      __metadata:
        label: "Memory request"
        description: "The memory request"
        type: "string"
        required: true
  limits:
    cpu:
      __metadata:
        label: "CPU limit"
        description: "The CPU limit"
        type: "string"
        required: true
    memory:
      __metadata:
        label: "Memory limit"
        description: "The memory limit"
        type: "string"
        required: true
